language: generic

services:
  - docker

stages:
  - build
  - deploy

build:
  provider: script
  script: make build
  on:
    branch: master

deploy:
  provider: script
  script: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD && make release
  on:
    branch: master
